import type { DashboardData } from "./types";

export const mockDashboardData: DashboardData = {
  live: {
    device_id: "xs-plug-001",
    timestamp: new Date().toISOString(),
    battery_percent: 72,
    battery_voltage: 48.2,
    battery_temperature: 25,
    battery_charging: true,
    battery_discharging: false,
    pv_voltage: 120.5,
    pv_current: 15.3,
    pv_power: 1847,
    load_power: 652,
    grid_power: 0,
    grid_status: "available",
    frequency: 50.1,
    ac_voltage: 230,
    today_production: 4.2,
    today_consumption: 2.1,
    relay_state: "closed",
    mode: "xense",
    device_online: "online",
    wifi_strength: -48,
    firmware_version: "v2.1.3",
    inverter_temperature: 38,
  },

  devices: [
    {
      id: "XS-PLUG-001",
      name: "XS-PLUG-001",
      appliance: "Air Conditioner",
      location: "Bedroom",
      status: "online",
      mode: "xense",
      power: 1200,
      signal: -52,
      online: true,
      relay_on: true,
    },
    {
      id: "XS-PLUG-002",
      name: "XS-PLUG-002",
      appliance: "Freezer",
      location: "Kitchen",
      status: "online",
      mode: "xense",
      power: 350,
      signal: -48,
      online: true,
      relay_on: false,
    },
    {
      id: "XS-PLUG-003",
      name: "XS-PLUG-003",
      appliance: "TV & Entertainment",
      location: "Living Room",
      status: "online",
      mode: "bypass",
      power: 150,
      signal: -68,
      online: true,
      relay_on: true,
    },
  ],

  decisions: [
    {
      id: 1,
      appliance: "Air Conditioner",
      icon: "snowflake",
      status: "on",
      reason: "Battery 72% · Solar 1.8 kW · Sufficient energy",
      time: "2:42 PM",
      load: 1200,
      confidence: "Optimal",
      priority: 4,
    },
    {
      id: 2,
      appliance: "Freezer",
      icon: "snowflake",
      status: "off",
      reason: "Battery 30% · Xense logic disconnected load",
      time: "1:15 PM",
      load: 350,
      confidence: "Required",
      duration: "1h 27m",
      priority: 3,
    },
    {
      id: 3,
      appliance: "Water Heater",
      icon: "shower",
      status: "standby",
      reason: "Insufficient solar (320 W) · Needs 2,000 W",
      time: "12:30 PM",
      load: 2000,
      confidence: "Pending",
      priority: 5,
    },
    {
      id: 4,
      appliance: "TV & Entertainment",
      icon: "tv",
      status: "on",
      reason: "Battery 68% · Low load (150 W) · Permitted",
      time: "3:00 PM",
      load: 150,
      confidence: "Favorable",
      priority: 3,
    },
  ],

  rules: [
    {
      id: 1,
      condition: "IF Battery > 80% AND Solar > 2,000 W",
      action: "Turn ON Air Conditioner",
      active: true,
      icon: "sun",
      iconBg: "rgba(52,211,153,0.1)",
      iconColor: "#34d399",
    },
    {
      id: 2,
      condition: "IF Battery < 35%",
      action: "Turn OFF Freezer & Water Heater",
      active: true,
      icon: "battery-low",
      iconBg: "rgba(248,113,113,0.1)",
      iconColor: "#f87171",
    },
    {
      id: 3,
      condition: "IF Grid Available AND Battery < 20%",
      action: "Switch to Automatic Mode (Grid)",
      active: true,
      icon: "bolt",
      iconBg: "rgba(251,191,36,0.1)",
      iconColor: "#fbbf24",
    },
    {
      id: 4,
      condition: "IF Time = 10:00 PM - 6:00 AM",
      action: "Turn OFF All Non-Essential Loads",
      active: false,
      icon: "clock",
      iconBg: "rgba(96,165,250,0.1)",
      iconColor: "#60a5fa",
    },
  ],

  priorities: [
    { rank: 1, name: "Refrigerator", power: 150, tag: "Essential", tagColor: "green", essential: true },
    { rank: 2, name: "Essential Lighting", power: 60, tag: "Essential", tagColor: "green", essential: true },
    { rank: 3, name: "Freezer", power: 350, tag: "High Priority", tagColor: "blue", essential: false },
    { rank: 4, name: "Air Conditioner", power: 1200, tag: "Medium", tagColor: "yellow", essential: false },
    { rank: 5, name: "Water Heater", power: 2000, tag: "Low Priority", tagColor: "red", essential: false },
  ],

  notifications: [
    {
      id: 1,
      icon: "bolt",
      iconBg: "rgba(52,211,153,0.1)",
      iconColor: "#34d399",
      title: "Grid Restored",
      description: "Power grid is back. System switched to Automatic Mode.",
      time: "2 min ago",
      unread: true,
    },
    {
      id: 2,
      icon: "battery-quarter",
      iconBg: "rgba(248,113,113,0.1)",
      iconColor: "#f87171",
      title: "Battery Low Alert",
      description: "Battery dropped to 30%. Xense logic disconnected Freezer.",
      time: "1h 15m ago",
      unread: true,
    },
    {
      id: 3,
      icon: "sun",
      iconBg: "rgba(251,191,36,0.1)",
      iconColor: "#fbbf24",
      title: "Solar Peak",
      description: "Solar production reached 2.4 kW. Air Conditioner turned ON.",
      time: "3h 30m ago",
      unread: false,
    },
    {
      id: 4,
      icon: "check",
      iconBg: "rgba(52,211,153,0.1)",
      iconColor: "#34d399",
      title: "Mode Changed",
      description: "System switched to Xense Mode automatically.",
      time: "5h ago",
      unread: false,
    },
    {
      id: 5,
      icon: "wifi",
      iconBg: "rgba(96,165,250,0.1)",
      iconColor: "#60a5fa",
      title: "Device Online",
      description: "XS-PLUG-003 reconnected. Signal strength: -68 dBm.",
      time: "Yesterday at 11:20 PM",
      unread: false,
    },
  ],

  chartData: [
    { time: "06:00", production: 0.1, consumption: 0.3 },
    { time: "07:00", production: 0.3, consumption: 0.4 },
    { time: "08:00", production: 0.8, consumption: 0.5 },
    { time: "09:00", production: 1.2, consumption: 0.4 },
    { time: "10:00", production: 1.8, consumption: 0.3 },
    { time: "11:00", production: 2.4, consumption: 0.2 },
    { time: "12:00", production: 3.1, consumption: 0.3 },
    { time: "13:00", production: 3.8, consumption: 0.4 },
    { time: "14:00", production: 4.2, consumption: 0.5 },
    { time: "15:00", production: 3.6, consumption: 0.6 },
    { time: "16:00", production: 2.9, consumption: 0.7 },
    { time: "17:00", production: 2.1, consumption: 0.8 },
    { time: "18:00", production: 1.2, consumption: 0.9 },
  ],

  totals: {
    total_production: 127.4,
    total_consumption: 89.2,
    energy_saved: 38.2,
    co2_avoided: 94,
    savings_percent: 30,
  },
};
